# -*- coding: utf-8 -*-
"""available_beds_in_hospital_problem04_group12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q4WK9QLDKEytIT88VxDahzh468BYDMx9
"""

# import and install packages
!pip install geopandas
import geopandas as gpd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn')

# read geographical data of germany
gdf = gpd.read_file('https://raw.githubusercontent.com/isellsoap/deutschlandGeoJSON/d677229523ef8ce7e9839909c0bca035618b05fa/2_bundeslaender/4_niedrig.geojson')
gdf.head()

plt.rcParams['figure.figsize'] = [16, 11]

# read data (source https://www.divi.de/register/tagesreport)
df = pd.read_csv('data.csv')
df.head()

# creating a map of germany
# every bubble represents one hospital in germany
# green bubble means there are free ICU beds
# orange bubble means there are just a few free ICU beds
# red bubble means there are no free ICU beds in this special hospital
plt.rcParams['figure.figsize'] = [25, 100]
fig, ax = plt.subplots()
gdf.plot(ax=ax, color='gray', alpha=0.3)
for i in range(len(df)):
  if df.loc[i, 'bettenStatus/statusHighCare'] == 'VERFUEGBAR':
    markercolor = 'green'
  elif df.loc[i, 'bettenStatus/statusHighCare'] == 'BEGRENZT':
    markercolor = 'orange'
  elif df.loc[i, 'bettenStatus/statusHighCare'] == 'NICHT_VERFUEGBAR':
    markercolor = 'red'

  ax.plot(
      df.loc[i, 'krankenhausStandort/position/longitude'],
      df.loc[i, 'krankenhausStandort/position/latitude'],
      marker='o',
      c = markercolor,
      alpha=0.5,
      markersize = df.loc[i, 'free_icu_beds_percent'] / 2
  )

